platform :ios, '9.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Wattpad/Podspecs.git'

target 'StoreKitManager' do
 pod 'RMStoreWP/AppReceiptVerifier', '0.7.1.1'
end
